version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: etc/testing/circle/install.sh
      - run: etc/testing/circle/start-minikube.sh
      - run: etc/testing/circle/deploy-pachyderm.sh
      - run: pachctl port-forward & npm run test
workflows:
  version: 2
  test:
    jobs:
      - test
